### ISSUE TITLE
Deel van de pagina is in het Duits

### ISSUE THREAD

**Issue by bef0re** [hatstack/hatstack-hexo#3]
zoals "Letzter Beitrag"

Komt dat doordat er een bestaand theme is gebruikt (zonder vermelding)?

**Comment by swordsecurity** [comment]
Ik denk dat de language niet helemaal goed is ingesteld in de _config.yml file, kan wel even naar kijken.

**Comment by bef0re** [comment]
fixed in commit be1df898522c5af7f0a28486bd79589cc7fd3af4

issue closed
